# Generated by Django 6.0.3 on 2026-04-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_baby_id_alter_devicestatus_id_and_more'),
        ('app', '0002_dailyuserstat'),
    ]

    operations = [
    ]
