# Generated by Django 5.2.8 on 2026-04-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # The merge commit referenced two different '0002' migrations from
        # separate branches. The other migration file wasn't present in this
        # checkout, which caused Django's migration graph to be inconsistent
        # (NodeNotFoundError). Depend only on the existing migration so the
        # graph is valid. If you later bring in the missing migration file,
        # we can revisit merging them properly.
        ('app', '0002_dailyuserstat'),
    ]

    operations = [
    ]
