# Generated by Django 4.2.26 on 2026-04-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_baby_id_alter_devicestatus_id_and_more'),
        ('app', '0002_dailyuserstat'),
    ]

    operations = [
    ]
