# Generated by Django 6.0.3 on 2026-04-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20260413_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserstat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
