# Generated by Django 4.2.26 on 2026-04-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20260414_1501'),
        ('app', '0004_alter_baby_id_alter_devicestatus_id_and_more'),
    ]

    operations = [
    ]
