# Generated by Django 6.0.3 on 2026-04-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='notification_frequency',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='default_max_heart_rate',
            field=models.IntegerField(default=160),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='default_min_heart_rate',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='default_min_oxygen_level',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='temperature_unit',
            field=models.CharField(choices=[('c', 'Celsius (°C)'), ('f', 'Fahrenheit (°F)')], default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms (kg)'), ('lb', 'Pounds (lb)')], default='kg', max_length=2),
        ),
    ]
