# Generated by Django 6.0.3 on 2026-04-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20260414_1501'),
        ('app', '0006_remove_userpreference_notification_frequency_and_more'),
    ]

    operations = [
    ]
