# Generated by Django 4.2.26 on 2026-04-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_feeding'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
