# Generated by Django 4.2.26 on 2026-04-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feeding_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaperLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('type', models.CharField(choices=[('Wet', 'Wet'), ('Dirty', 'Dirty'), ('Both', 'Both')], max_length=10)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diapers', to='app.baby')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
