# Generated by Django 4.2.26 on 2026-04-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_diaperlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleepsession',
            name='quality_score',
        ),
        migrations.AddField(
            model_name='sleepsession',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='sleepsession',
            name='position',
            field=models.CharField(choices=[('Back', 'Back'), ('Belly', 'Belly'), ('Side', 'Side')], default='Back', max_length=10),
        ),
    ]
