# Generated by Django 6.0.3 on 2026-04-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_feeding'),
        ('app', '0011_remove_userpreference_default_min_oxygen_level'),
    ]

    operations = [
    ]
