# Generated by Django 4.2.26 on 2026-04-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_sleepsession_quality_score_and_more'),
        ('app', '0012_merge_20260420_1858'),
    ]

    operations = [
    ]
