# Generated by Django 5.2.8 on 2026-04-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_feeding'),
        ('app', '0012_alter_baby_id_alter_comment_id_and_more'),
    ]

    operations = [
    ]
