# Generated by Django 5.2.8 on 2026-04-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20260420_1858'),
        ('app', '0013_merge_20260420_1553'),
    ]

    operations = [
    ]
