# Generated by Django 4.2.26 on 2026-04-22 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_community_communitymember_community_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('unit', models.CharField(choices=[('metric', 'Metric (kg, cm)'), ('imperial', 'Imperial (lbs, in)')], default='metric', max_length=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_logs', to='app.baby')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
