# Generated by Django 4.2.26 on 2026-04-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_growthlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='household',
        ),
        migrations.AddField(
            model_name='baby',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='Important medical facts like higher temperature baseline', null=True),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('times_per_day', models.IntegerField(default=1)),
                ('days_per_week', models.IntegerField(default=7)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='app.baby')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
