# Generated by Django 4.2.26 on 2026-04-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_baby_household_baby_medical_notes_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_notes', to='app.baby')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('baby', 'date')},
            },
        ),
    ]
