# Generated by Django 4.2.26 on 2026-04-24 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_dailynote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaperlog',
            name='type',
        ),
        migrations.AddField(
            model_name='diaperlog',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diaperlog',
            name='status',
            field=models.CharField(default='Pee', max_length=20),
        ),
        migrations.AlterField(
            model_name='diaperlog',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.baby'),
        ),
    ]
