# Generated by Django 6.0.3 on 2026-04-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userpreference_imperial_defaults'),
        ('app', '0019_remove_diaperlog_type_diaperlog_color_and_more'),
    ]

    operations = [
    ]
