# Generated by Django 4.2.26 on 2026-04-27 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_diaperlog_type_diaperlog_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={},
        ),
        migrations.RemoveField(
            model_name='medication',
            name='days_per_week',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='times_per_day',
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default='place-holder', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
