# Generated by Django 4.2.26 on 2026-04-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_medication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='medication',
            name='time',
        ),
        migrations.AddField(
            model_name='medication',
            name='days_per_week',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='medication',
            name='times_per_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
