# Generated by Django 5.2.8 on 2026-04-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_medication_options_remove_medication_time_and_more'),
        ('app', '0021_baby_household_alter_baby_id_alter_comment_id_and_more'),
    ]

    operations = [
    ]
